# Generated by Django 5.1.1 on 2024-11-10 04:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='company',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='fulltime',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='no_of_students',
        ),
        migrations.AddField(
            model_name='rounds',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='sample.company'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rounds',
            name='fulltime_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.fulltime'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='internship_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.internship'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='round_name',
            field=models.CharField(default='Not Mentioned', max_length=100),
        ),
        migrations.AddField(
            model_name='rounds',
            name='time_scheduled',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='round_no',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='type',
            field=models.IntegerField(choices=[(0, 'Intern'), (1, 'Full-time')]),
        ),
    ]
