# Generated by Django 5.1.1 on 2024-11-10 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_remove_rounds_comp_id_remove_rounds_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounds',
            name='applicant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_rounds', to='sample.applicants'),
        ),
    ]
