# Generated by Django 5.1.1 on 2024-11-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_rounds_applicant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounds',
            name='applicant_id',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='fulltime_id',
        ),
        migrations.RemoveField(
            model_name='rounds',
            name='internship_id',
        ),
        migrations.AddField(
            model_name='rounds',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sample.company'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='internship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.internship'),
        ),
        migrations.AddField(
            model_name='rounds',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.fulltime'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('FullTime', 'FullTime')], default=None, max_length=10),
        ),
    ]
