# Generated by Django 5.1.1 on 2024-11-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_remove_rounds_applicant_id_remove_rounds_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounds',
            name='internship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.internship'),
        ),
        migrations.AlterField(
            model_name='rounds',
            name='job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.fulltime'),
        ),
    ]
