# Generated by Django 5.1.1 on 2024-11-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_alter_applicants_internship_alter_applicants_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('notselected', 'Not Selected')], default='notselected', max_length=11),
        ),
    ]
