# Generated by Django 5.1.1 on 2024-11-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_applicants_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='designation_role',
        ),
    ]
