# Generated by Django 5.1.1 on 2024-11-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_remove_company_designation_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='package',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ph_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
