# Generated by Django 5.1.1 on 2024-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_remove_company_package_remove_company_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AddField(
            model_name='company',
            name='package',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
