# Generated by Django 5.1.1 on 2024-11-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_remove_company_email_company_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='package',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ph_number',
        ),
    ]
