# Generated by Django 5.1.1 on 2024-11-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_company_designation_role_company_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='designation_role',
        ),
        migrations.RemoveField(
            model_name='company',
            name='package',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
    ]
