# Generated by Django 5.1.1 on 2024-11-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0017_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
