# Generated by Django 5.1.1 on 2024-11-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_remove_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
