# Generated by Django 5.1.1 on 2024-11-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0020_remove_company_email_company_designation_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
