# Generated by Django 5.1.1 on 2024-11-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_alter_company_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user_id',
        ),
    ]
