# Generated by Django 5.1.1 on 2024-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_remove_faculty_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='package',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
