# Generated by Django 5.1.1 on 2024-11-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_remove_company_package_remove_company_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='designation_role',
        ),
    ]
