# Generated by Django 5.1.1 on 2024-11-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_remove_company_designation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ph_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
