# Generated by Django 5.1.1 on 2024-11-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_remove_faculty_staff_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
